.class public final Ls7/c$a;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Ls7/c;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(Ls7/c;I)[Ljava/lang/Object;
    .locals 0
    .param p0    # Ls7/c;
        .annotation build La8/l;
        .end annotation
    .end param
    .annotation build La8/l;
    .end annotation

    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Ls7/c<",
            "TT;>;I)[TT;"
        }
    .end annotation

    .line 1
    new-instance p0, Lh6/S;

    .line 2
    .line 3
    const-string p1, "Generated by Android Extensions automatically"

    .line 4
    .line 5
    invoke-direct {p0, p1}, Lh6/S;-><init>(Ljava/lang/String;)V

    .line 6
    .line 7
    .line 8
    throw p0
.end method
